// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "Tiburon":
            case "anim2":return [img`
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
......................................................
.....................fff..............................
.....................fcbf.............................
.....................fcbbf............................
.....................fccbbf...........................
.fffff................fcbbbf..........................
.fcbbcf...............fcbbbbf.........................
.fcbbbcf..............fcbbbbf.........................
..fccbbcf....ff.......fcbbbbbf........................
...fcbbbcf...fbf......fccbbbbf........................
...fcbbbbcf..fcbf...ffcccbbbbbffffffff................
....fcbbbbcfffccbfffcccccbbbbbbbbbbbbbffffffff........
....fcbbbbbbbbbccccccccbbbbbbbbbbbbbbbbbbbbbbbffff....
....fcbbbbbbbcccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbf...
...fccbbbbcccbcbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf..
...fcbbbcccbbcbcbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf.
..fcbbbfffccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf
..fbbbf...fccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcf
.fcbbf.....fccbbbbbbbbbbbbbbbbbbbbbbbbbbbf1fbbbbbbccf.
.fcbf.......fccbbbbbbbbbbbbbcbcbcbcbbbbbbfffbbbbcc1df.
.fff.........fcbbbbbbbbbbbbbbcbcbcbcbbbbbbbbbccc11df..
..............ffccccccbbbbbbbcbcbcbcbbbbbcccc1111df...
................f11111ccbbbbbcccccccccccc13131313f....
.................f11111cbbbbc1111111111113333333f.....
..................ff1ccbbbbc11111111111111ddddff......
...................fcbbbbbbcddddddddddddddffff........
................fffbbbbbbbbfffffffffffffff............
...............fbbbbbbbbbff...........................
................fbbbbbbff.............................
.................ffffff...............................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
