// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Tiburon0":
            case "anim1":return [img`
.......................................................
.....................fff...............................
.....................fcbf..............................
.....................fcbbf.............................
.....................fccbbf............................
.fffff................fcbbbf...........................
.fcbbcf...............fcbbbbf..........................
.fcbbbcf..............fcbbbbf..........................
..fccbbcf....ff.......fcbbbbbf.........................
...fcbbbcf...fbf......fccbbbbf.........................
...fcbbbbcf..fcbf...ffcccbbbbbffffffff.................
....fcbbbbcfffccbfffcccccbbbbbbbbbbbbbffffffff.........
....fcbbbbbbbbbccccccccbbbbbbbbbbbbbbbbbbbbbbbffff.....
....fcbbbbbbbcccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbf....
...fccbbbbcccbcbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf...
...fcbbbcccbbcbcbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf..
..fcbbbfffccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf.
..fbbbf...fccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcf.
.fcbbf.....fccbbbbbbbbbbbbbbbbbbbbbbbbbbbf1fbbbbbbccf..
.fcbf.......fccbbbbbbbbbbbbbcbcbcbcbbbbbbfffbbbbcc1df..
.fff.........fcbbbbbbbbbbbbbbcbcbcbcbbbbbbbbbccc11df...
..............ffccccccbbbbbbbcbcbcbcbbbbbcccc1111df....
................f11111ccbbbbbcccccccccccc13131313f.....
.................f11111cbbbbc1111111111113333333f......
..................ff1ccbbbbc11111111111111ddddff.......
...................fcbbbbbbcddddddddddddddffff.........
................fffbbbbbbbbfffffffffffffff.............
...............fbbbbbbbbbff............................
................fbbbbbbff..............................
.................ffffff................................
.......................................................
`];
            case "Tiburon1":
            case "anim2":return [img`
.......................................................
...............................fff.....................
..............................fbcf.....................
.............................fbbcf.....................
............................fbbccf.....................
...........................fbbbcf................fffff.
..........................fbbbbcf...............fcbbcf.
..........................fbbbbcf..............fcbbbcf.
.........................fbbbbbcf.......ff....fcbbccf..
.........................fbbbbccf......fbf...fcbbbcf...
.................ffffffffbbbbbcccff...fbcf..fcbbbbcf...
.........ffffffffbbbbbbbbbbbbbcccccfffbccfffcbbbbcf....
.....ffffbbbbbbbbbbbbbbbbbbbbbbbccccccccbbbbbbbbbcf....
....fbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccbbbbbbbcf....
...fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbcbcccbbbbccf...
..fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbcbcbbcccbbbcf...
.fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccfffbbbcf..
.fcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccf...fbbbf..
..fccbbbbbbf1fbbbbbbbbbbbbbbbbbbbbbbbbbbbccf.....fbbcf.
..fd1ccbbbbfffbbbbbbcbcbcbcbbbbbbbbbbbbbccf.......fbcf.
...fd11cccbbbbbbbbbcbcbcbcbbbbbbbbbbbbbbcf.........fff.
....fd1111ccccbbbbbcbcbcbcbbbbbbbccccccff..............
.....f31313131ccccccccccccbbbbbcc11111f................
......f3333333111111111111cbbbbc11111f.................
.......ffdddd11111111111111cbbbbcc1ff..................
.........ffffddddddddddddddcbbbbbbcf...................
.............fffffffffffffffbbbbbbbbfff................
............................ffbbbbbbbbbf...............
..............................ffbbbbbbf................
................................ffffff.................
.......................................................
`, img`
.......................................................
...............................fff.....................
..............................fbcf.....................
.............................fbbcf.....................
............................fbbccf.....................
...........................fbbbcf................fffff.
..........................fbbbbcf...............fcbbcf.
..........................fbbbbcf..............fcbbbcf.
.........................fbbbbbcf.......ff....fcbbccf..
.........................fbbbbccf......fbf...fcbbbcf...
.................ffffffffbbbbbcccff...fbcf..fcbbbbcf...
.........ffffffffbbbbbbbbbbbbbcccccfffbccfffcbbbbcf....
.....ffffbbbbbbbbbbbbbbbbbbbbbbbccccccccbbbbbbbbbcf....
....fbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccbbbbbbbcf....
...fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbcbcccbbbbccf...
..fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbcbcbbcccbbbcf...
.fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccfffbbbcf..
.fcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccf...fbbbf..
..fccbbbbbbf1fbbbbbbbbbbbbbbbbbbbbbbbbbbbccf.....fbbcf.
..fd1ccbbbbfffbbbbbbcbcbcbcbbbbbbbbbbbbbccf.......fbcf.
...fd11cccbbbbbbbbbcbcbcbcbbbbbbbbbbbbbbcf.........fff.
....fd1111ccccbbbbbcbcbcbcbbbbbbbccccccff..............
.....f31313131ccccccccccccbbbbbcc11111f................
......f3333333111111111111cbbbbc11111f.................
.......ffdddd11111111111111cbbbbcc1ff..................
.........ffffddddddddddddddcbbbbbbcf...................
.............fffffffffffffffbbbbbbbbfff................
............................ffbbbbbbbbbf...............
..............................ffbbbbbbf................
................................ffffff.................
.......................................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
